### ISSUE TITLE
yarn build failed (no clue with the js error desc...)

### ISSUE THREAD

**Issue by NovaZY** [Yuyz0112/sunmao-ui-go-binding#3]
Follow your blog, after yarn install,  yarn build failed, any suggestion please?
[ Win10 AMDX64, node 12, go 1.19.1 ]
BTW: comment out the error, I got a 409k css and 3,237k index.js, a FAT boy ...

...\sunmao-ui-go-binding-main\ui>yarn build
yarn run v1.22.19
$ tsc && vite build
src/App.tsx:33:11 - error TS2322: Type '() => ImplementedUtilMethod<any>[]' is not assignable to type 'UtilMethodFactory'.
  Type 'ImplementedUtilMethod<any>[]' is not assignable to type 'ImplementedUtilMethod<any>'.
    Type 'ImplementedUtilMethod<any>[]' is missing the following properties from type 'UtilMethod': version, kind, metadata, spec

33           () => {
             ~~~~~~~


Found 1 error in src/App.tsx:33

error Command failed with exit code 2.

**Comment by Yuyz0112** [comment]
fixed in the latest main branch

BTW, the bundle size after upgrade sunmao-ui:
```
dist/assets/index.512b3fc4.css                      408.67 KiB / gzip: 49.73 KiB
dist/assets/index.f62e7b92.js                       2328.17 KiB / gzip: 632.72 KiB
```

and this can be reduced when we support optional load component lib
